import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Output to Obsidian plugin folders
const OBSIDIAN_PLUGIN_PATH = "/Users/daviddiem/Documents/noterelay/note-relay-vault/.obsidian/plugins/noterelay";
const MAC_MINI_PLUGIN_PATH = "/Volumes/David's Mac mini._smb._tcp.local/Apps/obsidian/diemdb/.obsidian/plugins/noterelay";
const UI_BUNDLE_SOURCE = "../ui/dist/ui-bundle.js";
const UI_CSS_SOURCE = "../ui/dist/style.css";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/source.js"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: `${OBSIDIAN_PLUGIN_PATH}/main.js`,
  platform: "node",
});

if (prod) {
  await context.rebuild();
  
  // Copy built file back to repo root for GitHub distribution
  try {
    copyFileSync(`${OBSIDIAN_PLUGIN_PATH}/main.js`, "main.js");
    console.log("✓ Copied main.js to repo root");
  } catch (err) {
    console.error("Failed to copy main.js to repo root:", err);
  }
  
  // Copy manifest
  try {
    copyFileSync("manifest.json", `${OBSIDIAN_PLUGIN_PATH}/manifest.json`);
    console.log("✓ Copied manifest.json");
  } catch (err) {
    console.error("Failed to copy manifest.json:", err);
  }
  
  // Copy UI bundle files (if they exist)
  try {
    if (existsSync(UI_BUNDLE_SOURCE)) {
      copyFileSync(UI_BUNDLE_SOURCE, `${OBSIDIAN_PLUGIN_PATH}/ui-bundle.js`);
      console.log("✓ Copied ui-bundle.js (358 KB)");
    } else {
      console.warn("⚠️  UI bundle not found - run `npm run build` in note-relay-ui first");
    }
  } catch (err) {
    console.error("Failed to copy ui-bundle.js:", err);
  }
  
  try {
    if (existsSync(UI_CSS_SOURCE)) {
      copyFileSync(UI_CSS_SOURCE, `${OBSIDIAN_PLUGIN_PATH}/style.css`);
      console.log("✓ Copied style.css (28 KB)");
    }
  } catch (err) {
    console.error("Failed to copy style.css:", err);
  }
  
  console.log("✅ Built to Obsidian plugin folder");
  
  // Copy to Mac mini if mounted
  try {
    copyFileSync(`${OBSIDIAN_PLUGIN_PATH}/main.js`, `${MAC_MINI_PLUGIN_PATH}/main.js`);
    copyFileSync("manifest.json", `${MAC_MINI_PLUGIN_PATH}/manifest.json`);
    if (existsSync(UI_BUNDLE_SOURCE)) {
      copyFileSync(UI_BUNDLE_SOURCE, `${MAC_MINI_PLUGIN_PATH}/ui-bundle.js`);
      copyFileSync(UI_CSS_SOURCE, `${MAC_MINI_PLUGIN_PATH}/style.css`);
    }
    console.log("✅ Also copied to Mac mini");
  } catch (err) {
    console.log("⚠️  Mac mini not mounted (skipping)");
  }
  
  process.exit(0);
} else {
  await context.watch();
  console.log("👀 Watching for changes...");
}
